# Generated by Django 6.0.2 on 2026-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_summited_task_created_by_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='completed_by_student',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
